export const DISCOVERY_PATHS = [
  // Roots
  "/",
  "/api",
  "/api/v1",
  "/api/v2",
  "/v1",
  "/v2",

  // Swagger / Docs
  "/api-docs",
  "/docs",
  "/swagger",
  "/swagger.json",
  "/swagger.yaml",
  "/api/swagger.json",
  "/api/swagger.yaml",
  "/api/v1/swagger.json",
  "/api/docs",
  "/openapi.json",
  "/api/openapi.json",
  "/api/v1/openapi.json",

  // GraphQL
  "/graphql",
  "/api/graphql",
  "/api/v1/graphql",
  "/v1/graphql",
  "/graphiql",
  "/api/graphiql",

  // Auth & Session
  "/auth",
  "/auth/login",
  "/auth/register",
  "/auth/signup",
  "/api/auth",
  "/api/auth/login",
  "/api/auth/register",
  "/api/auth/user",
  "/api/auth/me",
  "/api/login",
  "/api/register",
  "/api/signup",
  "/api/signin",
  "/api/logout",
  "/api/session",
  "/api/user/me",
  "/api/users/current",
  "/api/whoami",

  // Users & Profiles
  "/user",
  "/users",
  "/profile",
  "/me",
  "/api/user",
  "/api/users",
  "/api/profile",
  "/api/profiles",
  "/api/me",
  "/api/v1/user",
  "/api/v1/users",
  "/api/v1/me",
  "/api/account",
  "/api/accounts",
  "/api/v1/account",
  "/api/v1/accounts",

  // Admin
  "/admin",
  "/administrator",
  "/api/admin",
  "/api/administrator",
  "/api/v1/admin",
  "/admin/dashboard",
  "/dashboard",

  // System & Health
  "/health",
  "/healthz",
  "/status",
  "/info",
  "/api/health",
  "/api/healthz",
  "/api/status",
  "/api/info",
  "/actuator",
  "/actuator/health",

  // Config & Secrets
  "/config.json",
  "/api/config",
  "/api/settings",
  "/settings",

  // Uploads & Files
  "/upload",
  "/uploads",
  "/api/upload",
  "/api/uploads",
  "/files",
  "/api/files",

  // Common Resources
  "/api/posts",
  "/api/articles",
  "/api/items",
  "/api/products",
  "/api/orders",
  "/api/carts",
  "/api/notifications",
  "/api/messages",
  "/api/search",
  "/api/logs",

  // Standard V1 variations
  "/api/v1/auth/login",
  "/api/v1/login",
  "/api/v1/signup",
  "/api/v1/health",
  "/api/v1/status",
  "/api/v1/upload",

  // Robots & Sitemaps
  "/robots.txt",
  "/sitemap.xml",
  "/.well-known/security.txt",
  "/.well-known/openid-configuration",
];
